services:
  # ส่วนของหน้าบ้าน
  frontend-service:
    build:
      context: ./frontend/frtPws
      dockerfile: Dockerfile
    ports:
      - "3210:5173"
    volumes:
      - ./frontend/frtPws:/app
      - /app/node_modules
    networks:
      - pwfatigue
    environment:
      - CHOKIDAR_USEPOLLING=true # ช่วยให้ Docker บน Windows มองเห็นการเซฟไฟล์ได้ไวขึ้น
    restart: unless-stopped

  # ส่วนของหลังบ้าน
  backend-service:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - pwfatigue
    restart: unless-stopped

# สร้างวง Network เพื่อให้หน้าบ้านกับหลังบ้านคุยกันได้
networks:
  pwfatigue:
    driver: bridge